# Production-specific patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cve-evaluation
spec:
  template:
    spec:
      containers:
      - name: evaluation
        # Production command (submit results)
        args:
          - "--mode"
          - "api"
          - "--limit"
          - "50"
          - "--stages"
          - "all"
          - "--submit"

        # Higher resource limits for production
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

      # Production pod anti-affinity (spread across nodes)
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cve-evaluation
              topologyKey: kubernetes.io/hostname
